name: ussd_uz
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0-nullsafety
  get_it: ^6.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  shared_preferences: ^2.0.5
  dio: ^3.0.10
  share: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

